apiVersion: v1
kind: Service
metadata:
  name: donimoney
  labels:
    app: donimoney
spec:
  type: LoadBalancer
  selector:
    app: donimoney
  ports:
    - name: http
      port: 80 #외부 노출 포트
      targetPort: 3000  #컨테이너 포트

